# Generated by Django 4.1.5 on 2023-01-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='21 Sophia Cres, North Rocks, NSW 2151'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(default='I am awesome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.URLField(default='https://tada.com'),
            preserve_default=False,
        ),
    ]
