# Generated by Django 4.1.5 on 2023-01-21 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 11, 34, 9, 739026)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_endtime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 11, 34, 25, 157802)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_starttime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 11, 34, 34, 286102)),
            preserve_default=False,
        ),
    ]
