# Generated by Django 4.1.5 on 2023-01-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_date_project_project_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(),
        ),
    ]
